name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v3

          
      - name: install boost
        run: |
          brew install boost

      - name: build
        run: |
          ./run.sh
          
      - name: test
        run: |
          ./build/tests
